import { GeneratorOptions, ParsedClass, ParsedProperty } from '../types';
import { toCamelCase, toPascalCase } from './naming';

const ISO_DATE_REGEX = /^\d{4}-\d{2}-\d{2}(T\d{2}:\d{2}:\d{2}(\.\d+)?(Z|[+-]\d{2}:?\d{2})?)?$/;

/**
 * Checks if a string is a valid ISO 8601 date-time string
 */
export function isIsoDate(val: string): boolean {
  return typeof val === 'string' && val.length >= 10 && ISO_DATE_REGEX.test(val) && !isNaN(Date.parse(val));
}

/**
 * Merges multiple object samples from a JSON array to ensure all possible fields are captured.
 */
function mergeObjectArray(arr: unknown[]): Record<string, unknown> {
  const merged: Record<string, unknown> = {};
  for (const item of arr) {
    if (item && typeof item === 'object' && !Array.isArray(item)) {
      for (const [k, v] of Object.entries(item as Record<string, unknown>)) {
        if (!(k in merged) || merged[k] === null || merged[k] === undefined) {
          merged[k] = v;
        } else if (typeof v === 'object' && v !== null && typeof merged[k] === 'object' && merged[k] !== null) {
          if (Array.isArray(v) && Array.isArray(merged[k])) {
            merged[k] = [...(merged[k] as unknown[]), ...v];
          }
        }
      }
    }
  }
  return merged;
}

export class JsonToAstParser {
  private classesMap: Map<string, ParsedClass> = new Map();
  private classCountMap: Map<string, number> = new Map();

  constructor(private options: GeneratorOptions) {}

  /**
   * Generates a unique Class name to prevent collisions
   */
  private getUniqueClassName(baseName: string): string {
    const pascal = toPascalCase(baseName);
    if (!this.classCountMap.has(pascal)) {
      this.classCountMap.set(pascal, 1);
      return pascal;
    }
    const count = this.classCountMap.get(pascal)! + 1;
    this.classCountMap.set(pascal, count);
    return `${pascal}${count}`;
  }

  /**
   * Main entry point to parse raw JSON into a list of ParsedClass objects
   */
  public parse(jsonInput: unknown): ParsedClass[] {
    this.classesMap.clear();
    this.classCountMap.clear();

    const rootName = toPascalCase(this.options.rootClassName || 'AutogeneratedModel');

    if (Array.isArray(jsonInput)) {
      if (jsonInput.length === 0) {
        // Empty array
        const rootClass: ParsedClass = {
          className: rootName,
          properties: [
            {
              jsonKey: 'items',
              dartFieldName: 'items',
              dartType: 'List<dynamic>',
              isNullable: this.options.nullability === 'nullable',
              isList: true,
              isObject: false,
              isMap: false,
              isDateTime: false,
              isPrimitiveList: true,
              isObjectList: false,
              listElementType: 'dynamic',
              originalValue: [],
            },
          ],
        };
        return [rootClass];
      }

      const firstElem = jsonInput[0];
      if (firstElem && typeof firstElem === 'object' && !Array.isArray(firstElem)) {
        const mergedObj = mergeObjectArray(jsonInput);
        this.parseObject(rootName, mergedObj);
      } else {
        // Primitive list root
        const elemType = this.inferPrimitiveType(firstElem);
        const rootClass: ParsedClass = {
          className: rootName,
          properties: [
            {
              jsonKey: 'data',
              dartFieldName: 'data',
              dartType: `List<${elemType}>`,
              isNullable: this.options.nullability === 'nullable',
              isList: true,
              isObject: false,
              isMap: false,
              isDateTime: false,
              isPrimitiveList: true,
              isObjectList: false,
              listElementType: elemType,
              originalValue: jsonInput,
            },
          ],
        };
        return [rootClass];
      }
    } else if (jsonInput && typeof jsonInput === 'object') {
      this.parseObject(rootName, jsonInput as Record<string, unknown>);
    } else {
      // Primitive root
      const rootClass: ParsedClass = {
        className: rootName,
        properties: [
          {
            jsonKey: 'value',
            dartFieldName: 'value',
            dartType: this.inferPrimitiveType(jsonInput),
            isNullable: this.options.nullability === 'nullable',
            isList: false,
            isObject: false,
            isMap: false,
            isDateTime: false,
            isPrimitiveList: false,
            isObjectList: false,
            originalValue: jsonInput,
          },
        ],
      };
      return [rootClass];
    }

    return Array.from(this.classesMap.values());
  }

  private parseObject(className: string, obj: Record<string, unknown>): ParsedClass {
    const existing = this.classesMap.get(className);
    if (existing) {
      return existing;
    }

    const properties: ParsedProperty[] = [];
    const parsedClass: ParsedClass = {
      className,
      properties,
      originalSample: obj,
    };

    // Register class early to handle circular references or recursive data structures
    this.classesMap.set(className, parsedClass);

    for (const [key, value] of Object.entries(obj)) {
      const prop = this.parseProperty(key, value, className);
      properties.push(prop);
    }

    return parsedClass;
  }

  private parseProperty(key: string, value: unknown, _parentClassName: string): ParsedProperty {
    const dartFieldName = toCamelCase(key);
    let dartType = 'dynamic';
    let isNullable = this.options.nullability === 'nullable';
    let isList = false;
    let isObject = false;
    const isMap = false;
    let isDateTime = false;
    let isPrimitiveList = false;
    let isObjectList = false;
    let nestedClassName: string | undefined;
    let listElementType: string | undefined;

    if (value === null || value === undefined) {
      dartType = 'dynamic';
      isNullable = true;
    } else if (typeof value === 'boolean') {
      dartType = 'bool';
      if (this.options.nullability === 'smart') isNullable = false;
    } else if (typeof value === 'number') {
      if (Number.isInteger(value)) {
        dartType = 'int';
      } else {
        dartType = 'double';
      }
      if (this.options.nullability === 'smart') isNullable = false;
    } else if (typeof value === 'string') {
      if (isIsoDate(value)) {
        dartType = 'DateTime';
        isDateTime = true;
      } else {
        dartType = 'String';
      }
      if (this.options.nullability === 'smart') isNullable = false;
    } else if (Array.isArray(value)) {
      isList = true;
      if (this.options.nullability === 'smart') isNullable = false;

      if (value.length === 0) {
        dartType = 'List<dynamic>';
        listElementType = 'dynamic';
        isPrimitiveList = true;
      } else {
        const sampleItem = value[0];
        if (sampleItem && typeof sampleItem === 'object' && !Array.isArray(sampleItem)) {
          // List of objects
          isObjectList = true;
          const childNameCandidate = toPascalCase(key);
          const childClassName = this.getUniqueClassName(childNameCandidate);
          const merged = mergeObjectArray(value);
          this.parseObject(childClassName, merged);
          
          nestedClassName = childClassName;
          listElementType = childClassName;
          dartType = `List<${childClassName}>`;
        } else if (Array.isArray(sampleItem)) {
          // List of Lists
          dartType = 'List<List<dynamic>>';
          listElementType = 'List<dynamic>';
          isPrimitiveList = true;
        } else {
          // List of primitives
          const primType = this.inferPrimitiveType(sampleItem);
          listElementType = primType;
          isPrimitiveList = true;
          dartType = `List<${primType}>`;
        }
      }
    } else if (typeof value === 'object') {
      // Nested Single Object
      isObject = true;
      if (this.options.nullability === 'smart') isNullable = false;

      const childNameCandidate = toPascalCase(key);
      const childClassName = this.getUniqueClassName(childNameCandidate);
      this.parseObject(childClassName, value as Record<string, unknown>);

      nestedClassName = childClassName;
      dartType = childClassName;
    }

    if (this.options.nullability === 'non_nullable') {
      isNullable = false;
    } else if (this.options.nullability === 'nullable') {
      isNullable = true;
    }

    return {
      jsonKey: key,
      dartFieldName,
      dartType,
      isNullable,
      isList,
      isObject,
      isMap,
      isDateTime,
      isPrimitiveList,
      isObjectList,
      nestedClassName,
      listElementType,
      originalValue: value,
    };
  }

  private inferPrimitiveType(val: unknown): string {
    if (val === null || val === undefined) return 'dynamic';
    if (typeof val === 'boolean') return 'bool';
    if (typeof val === 'number') return Number.isInteger(val) ? 'int' : 'double';
    if (typeof val === 'string') return isIsoDate(val) ? 'DateTime' : 'String';
    return 'dynamic';
  }
}
